FROM alpine:3.2

RUN apk add --update ca-certificates
RUN apk add xmlsec --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/
RUN ln -s libxmlsec1-openssl.so.1 /usr/lib/libxmlsec1-openssl.so


ENV HOME=/app
ENV GO15VENDOREXPERIMENT 1
ENV BUILD_DIR=/app/build
ENV NODE_ENV=production

RUN mkdir /app
ADD main /app/
ADD build /app/build/

EXPOSE 80
ENTRYPOINT ["/app/main"]
